### ISSUE TITLE
Over-clustering of transcripts in gene-dense genomes

### ISSUE THREAD

**Issue by Adamtaranto** [GenomeRIK/tama#10]
Hi Richard,

Re our discussion at PAG about what should constitute a "gene" for the purpose of transcript clustering, I wanted to note some issues that might arise from TAMAs default rule of "cluster everything with any overlap".

1) Fungal genomes frequently contain genes with overlapping UTRs. This is a known issue for transcript assembly (cufflinks) and RNA-seq guided gene annotation. See [CodingQuarry](https://doi.org/10.1186/s12864-015-1344-4) paper for details.

One potential solution might be to first predict the CDS region of a transcript then cluster transcripts with shared exons within the CDS, ignoring UTRs.

Alternatively, for well-annotated genomes where the user is just wanting to incorporate novel isoforms of existing genes, you might just assign transcripts to the reference gene that they have the greatest overlap with. 

2) Transcripts fully contained within an intron of another gene (no CDS overlap) are assigned to the same cluster as the gene they are nested in. This would call things like homing endonucleases from mobile-intron elements as isoforms of whatever gene they are inserted in. The same issue would also come up where other TEs insert into an existing intron.

I think using a CDS overlap rule for clustering would also work here.

**Comment by GenomeRIK** [comment]
Hi Adam,

It was great meeting you and discussing transcriptome stuff with you at PAG!

Regarding your questions/suggestions:

>>1. Fungal genomes frequently contain genes with overlapping UTRs. This is a known issue for >>transcript assembly (cufflinks) and RNA-seq guided gene annotation. See CodingQuarry paper >>for details.

This is great to know! Haven't had any contact with fungal genomes so I will definitely need to figure out how to address this aspect for the fungal peoples.

>>One potential solution might be to first predict the CDS region of a transcript then cluster >>transcripts with shared exons within the CDS, ignoring UTRs.

Actually, if you run the ORF/NMD pipelines it pretty much does this. The "Gene ID's" will not change but the information for matching protein will be present which can be used to tease out these overlapping genes.

>>Alternatively, for well-annotated genomes where the user is just wanting to incorporate novel >>isoforms of existing genes, you might just assign transcripts to the reference gene that they have >>the greatest overlap with.

This is an interesting idea but I would need to learn a bit more about how the transcript models present in fungal genomes to assess this method. 

>>Transcripts fully contained within an intron of another gene (no CDS overlap) are assigned to the >>same cluster as the gene they are nested in. This would call things like homing endonucleases >>from mobile-intron elements as isoforms of whatever gene they are inserted in. The same issue >>would also come up where other TEs insert into an existing intron.

I am not sure I understand what you are saying here. Are you saying that transcripts within the intronic region of another gene should be grouped with that gene? Or they should not? In TAMA they would not be group because it requires exonic overlap. 

>>I think using a CDS overlap rule for clustering would also work here.

Could you explain this in more detail? Or perhaps this will make sense to me once I understand your previous statement. 

I think in order for me to understand how best to adjust the tools for Fungal genomes, I would need to see Iso-Seq data from fungal species. Do you know of any such datasets?

Cheers,
Richard
