### ISSUE TITLE
Evidence for CDS selection

### ISSUE THREAD

**Issue by Adamtaranto** [GenomeRIK/tama#11]
TAMA currently uses identity to Uniprot proteins to select ORFs/CDSs. For genes without a homologue in Uniprot, it would great to be able to incorporate other lines of evidence.

- Use custom reference protein sets (i.e. from a related species) in place of Uniprot data.

- Select ORFs that contain a PFAM domain hit (as is done in [transdecoder](https://github.com/TransDecoder/TransDecoder/wiki))

- Select ORFs with best Kozak sequence match for that genome. The Kozak consensus can be obtained from the high-confidence homologues of Uniprot matches. ( [CodingQuarry](https://doi.org/10.1186/s12864-015-1344-4) trains a GHMM for this.)

**Comment by GenomeRIK** [comment]
Hi Adam,

>>TAMA currently uses identity to Uniprot proteins to select ORFs/CDSs. For genes without a >>homologue in Uniprot, it would great to be able to incorporate other lines of evidence.

Yes I think this should definitely be the next update for the ORF/NMD pipeline. 

>>Use custom reference protein sets (i.e. from a related species) in place of Uniprot data.

Since it will be too time consuming to accommodate parsing from all the different sources, what I think I will do is ask for the information to be formatted in a certain way for inputing to the pipeline. 

>>Select ORFs that contain a PFAM domain hit (as is done in transdecoder)

This is a bit problematic for me due to my interest in sense exonic lncRNA however, I think I could implement this as an additional step for special use cases. I will go into detail about why this is a bit tricky in my blog once I get that running (thanks for your suggestion and support on the blog!). 

>>Select ORFs with best Kozak sequence match for that genome. The Kozak consensus can be >>obtained from the high-confidence homologues of Uniprot matches. ( CodingQuarry trains a >>GHMM for this.)

This is an excellent idea! I will have to look into this more. 

Unfortunately, right now I am bogged down with some other projects so I am not sure when I will get around to doing this however, I will put it on my to do list and if more people show interest in these features I will bump it up for priority. 

Do you have any plans for developing something like this?

Cheers,
Richard
