### ISSUE TITLE
Forking and converting to Python3

### ISSUE THREAD

**Issue by lucventurini** [GenomeRIK/tama#12]
Dear @GenomeRIK ,
                                   I have had a look to your code recently as I am looking for solutions to improve the alignment of NanoPore reads to the genome prior feeding them into our RNASeq transcript annotation and model selection pipeline, [Mikado](https://github.com/EI-CoreBioinformatics/mikado) and its associated [gene annotation pipeline](https://github.com/EI-CoreBioinformatics/mikado). Our team (@swarbred, @cschuh and @gemygk) is interested in testing TAMA for this purpose.

After looking at the code, though, I would like to perform some changes (port to Python3, use PySam to read directly BAM files, and potentially others after I start working on it). Would we have your permission to do so and introduce the forked program, of course properly cited both in the code and in a possible future publication, in our workflows?

**Comment by GenomeRIK** [comment]
Hello Luca,

Thank you for very much for contacting me. I'm honoured that you are interested in incorporating TAMA into your Mikado annotation pipelines. You may of course fork TAMA and make changes as are needed for your purposes. Can I ask however to be included in this work? I am still making updates to TAMA by adding new features and I would like to try to pass these features on to any forked code. 

I had actually intended on incorporating PySam to be able to take the bam files directly and to handle the sorting within the code but I just haven't gotten around to it since I wanted to make it so that people who did not have up-to-date python libraries could easily opt out of the PySam route. 

There are also some things I want to improve to provide more accuracy while retaining sensitivity. I believe these future changes will make TAMA the most useful tool for processing long read transcript sequencing data after mapping. It is these changes that I would like to make sure will be applied to all TAMA forks as I would like to avoid situations where users become frustrated with major feature differences between versions. Likewise I would like permission to incorporate major features that you add into the main code to keep a level of consistency across the TAMA flavours. Will this be ok with you?

Also I am currently writing up a manuscript for publishing TAMA. So there will be a citable paper coming out soon hopefully. 

Thank you,
Richard

**Comment by GenomeRIK** [comment]
Hi Luca,
Just to let you know I have updated TAMA collapse to be able to work with BAM input now. 

Cheers,
Richard
