### ISSUE TITLE
color of transcripts in merge bed file?

### ISSUE THREAD

**Issue by chenzler** [GenomeRIK/tama#13]
What do the transcript colors represent for the TAMA collapse and merge output bed files? I can't seem to find it explained in the wiki. Thanks!

**Comment by GenomeRIK** [comment]
Hi,

Thanks for bringing this up. I forgot to explain this in the wiki. I have added the information now. 

Basically the colours represent the number of source support for each transcript model after merging. TAMA Collapse output models should all be red since it should represent a single source.

So the colour definitions are:
1 = red
2 = orange
3 = yellow
4 = lime
5 = light turquoise 
6 = light blue
7 = royal blue
8 = dark blue
9 = dark purple
10 = magenta

This was just a way to make it easier to see how supported each transcript model was in a genome browser. 

Cheers,
Richard

**Comment by chenzler** [comment]
Thank you!!

**Comment by GenomeRIK** [comment]
Hi Chenzler,

Sorry I just realized I made a mistake when explaining the colours of the transcript models. The colours represent the individual source for each transcript. So source 1 would be red and source 2 would be orange. But if there are mutliple sources then it would be coloured magenta.

1 = red
2 = orange
3 = yellow
4 = lime
5 = light turquoise
6 = light blue
7 = royal blue
8 = dark blue
9 = dark purple
Multiple Sources = magenta

I have changed the wiki to reflect this. My apologies for the misinformation. 

Thank you,
Richard
