### ISSUE TITLE
TAMA without a reference genome

### ISSUE THREAD

**Issue by emaleckova** [GenomeRIK/tama#15]
Hello everyone,

I am new in the field of bioinformatics and currently working with my fist Iso-Seq data. I have obtained what might be an OK reference transcriptome but I am searching for ways to improve it. The TAMA tool got my attention and I would like to give it a try, but the problem is we do not have a reference transcriptome for our species of interest. When using Cogent in such a situation as described [here](https://github.com/Magdoll/Cogent/wiki/Tutorial:-Using-Cogent-to-collapse-redundant-transcripts-in-absence-of-genome), a fake genome is created first prior to isoform collapsing. My question is, is there is a similar "workaround" with TAMA as well. Or could I use the Cogent-based fake genome and then proceed with TAMA collapse?

Many thanks for sharing your opinions/ideas with me.

Best,
Eva

**Comment by GenomeRIK** [comment]
Hi Eva,

Thank you for considering TAMA. You could theoretically use TAMA Collapse to replace the "collapse_isoforms_by_sam.py" step shown in that tutorial. I'm not sure what parameters would be best so I think it would be a good idea to play around with the wobble settings and the coverage and identity thresholds. 

Some things to keep in mind for this pipeline:
1. Minimap2 tries to map splice junctions using the canonical GT-AG intron signals. Since the fake cogent genome will probably not have introns represented, this may throw off the splice junction mapping. This means there is a high probability that your reconstructed transcript sequences will have frame shifts from the erroneous splice junctions. So if you are doing downstream analysis of coding potential and identifying coding regions this will need to be dealt with somehow. 

2. The gene models will not be real. Transcripts grouped together in genes will not represent actual genes. So I would recommend not using the gene level information or using it as only a small indication of how many genes there are. This is due to gene families and genes with similar domains. 

3. I think the TAMA collapse variant output files will be very useful here. If you analyse them, you may be able to see how the fake genome may have changed the actual transcript sequences. So you may be able to use the variant files to correct the transcript sequences for coding analysis. If you want some help with this step just email me when you get to that point and I can have a look. 

4. It will be difficult to differentiate real transcripts from genomic contamination using the fake genome. Similarly the exonic structures will be basically useless. So basically the only thing you get from this pipeline is some elementary/dubious gene grouping and the consensus transcript sequences. That is still useful, but I would be weary to try not to "over use" the data by trying to analyse things that are basically eradicated using this pipeline. For instance, running SQANTI on the output of this pipeline would be useless as far as I can see.

Hope this helps and let me know if you have any more questions or suggestions. 

Thank you,
Richard

**Comment by GenomeRIK** [comment]
Hi Eva,

It looks like it has been a while since my response so I am going to close this issue now. If you need more help with this you can either continue on this thread or make another issue post. 

Thank you,
Richard
