### ISSUE TITLE
MemoryError problem

### ISSUE THREAD

**Issue by rmenafra** [GenomeRIK/tama#18]
Hi Rik,
I have my first Isoseq dataset from a Sequel2 run, this is a set of 2 samples prepped with the TeloPrime protocol (5'-cap). I have 2 main questions:
1)
I went through your instructions at https://github.com/GenomeRIK/tama/wiki/TAMA-GO:-Sequence-Cleanup up to the collapsing stage. I mapped the data using minimap2. Aligned reads are 3470490 for  sample1 and 4068057 for sample2.
For 1 sample at the Tama_collapse stage I've got an error saying:
"var_coverage_dict[scaffold][this_coord][trans_id] = 1
MemoryError"

This job was run on a cluster, allocating 240gb of memory.
 Tama_collapse on sample1 failed with the above mentioned message and on sample2 is running since a week (I allocated 480gb for the second job).
Attached you will find the output log of the sample that failed.
Do you have any suggestion on how to solve/improve this?

2)Is there a way with your set of tools to annotate the trascripts to a reference gff/gtf file?
Thanks in advance for your time.
I'm looking forward to your reply.
Cheers,
Roberta
[Tama_collapse.o5180769.zip](https://github.com/GenomeRIK/tama/files/4147759/Tama_collapse.o5180769.zip)

**Comment by GenomeRIK** [comment]
Hi Roberta,

Thank you for using TAMA. 

To address your questions:

1) TAMA Collapse is very memory greedy at the moment. I am working on optimizing it but in the meantime I suggest using the sam/bam splitter tool before running TAMA Collapse. 

You can find instructions here:
https://github.com/GenomeRIK/tama/wiki/TAMA-GO:-Split-Files

Basically it will split the sam file into smaller sam files based on contiguity (so no effect on end result). After you run TAMA Collapse on each split sam file you can then merge the results using TAMA Merge. 

2) I am not sure I completely understand what you mean by this. There are many ways to do this. However, if you want to know which Iso-Seq models match a reference GFF/GTF file then you can use TAMA Merge to get this information.  You will need to convert the GFF/GTF file into BED12 first though. 

Since the GFF/GTF formats are more loosely define than BED12 there is no universal convertor. However, I have made some convertors which you can read about here:
https://github.com/GenomeRIK/tama/wiki/TAMA-GO:-Formatting

If you use one of the convertors, make sure you are using one that is specific to the specific GFF/GTF format you are using. If you are unsure, just let me know what the source for the GFF/GTF file is (ie Ensembl, Stringtie, etc).

When running TAMA Merge, if you want to pull the names of the Genes and Transcripts from the reference GFF/GTF, use the -s parameter. You can read more about it in the wiki page for TAMA Merge. 

Hope that helps. Let me know if you have any issues with that or more questions. 

Cheers,
Richard

**Comment by rmenafra** [comment]
Hi Richard,
thanks for your reply.
Would there be any way to estimate how much memory/processor I would (roughly) need to allocate based on your experience?  Or in how many sub-files should I split my big  alignment file?
For the second point indeed I meant to be able to connect the transcript ID with a "known" gene name from the reference genome. I will try to do the conversion and see how it works, if I get to the Tama_merge.
Cheers,
Roberta

**Comment by GenomeRIK** [comment]
Hi Roberta,

>>Would there be any way to estimate how much memory/processor I would (roughly) need to allocate based on your experience?

Good question! I am ashamed to say that I have not been paying attention to estimating so much. I tend to just throw a lot at it. However, for 300K reads you should be safe with 24 hours processing time and 100 GB memory. But there is an exception, if you have over abundant genes the processing time will increase exponentially. 

>>Or in how many sub-files should I split my big alignment file?

I usually split into 10 or more files. 

>>For the second point indeed I meant to be able to connect the transcript ID with a "known" gene name from the reference genome. I will try to do the conversion and see how it works, if I get to the Tama_merge.

You will get to TAMA Merge! Just split the sam into 10 or more files, run individually, and then merge. The runs will finish pretty quickly after you split. However, I suspect you have some over-abundant genes, so one or more of the splits may take longer than the others. Most of them should finish within a day or sooner. 

By the way, are you using the -x capped parameter? Do you mind sharing your command so I can see if there is anything you can do to optimize?

Cheers,
Richard

**Comment by rmenafra** [comment]
Hi Richard,
of course, here is my latest command:
```bash
#!/bin/bash
#$ -S /bin/bash
#$ -q all.q
#$ -N Tama_collapse
#$ -l h_vmem=60G
#$ -pe BWA 8
#$ -cwd
#$ -j Y
#$ -V


INPUT=path_to_input.bam
REF=path_to_ref.fa

source activate pbbioconda
python /exports/lgtc/projects/Roberta/tama/tama_collapse.py -s $INPUT  -f $REF  -b BAM -p collapsed_Isoseq_16hr_no_alt -x capped
I will try splitting and let you know!
Thanks for your help

**Comment by GenomeRIK** [comment]
Hi Roberta,

Ok, that seems ok for now. Did the split runs finish ok?

Cheers,
Richard

**Comment by rmenafra** [comment]
Hi Richard,
I managed to split but didn't collapse them yet.
I will post as soon as it finish.
Best,
Roberta

**Comment by GenomeRIK** [comment]
Hi Roberta,

Haha ok you stumbled upon a debate I was having with someone else about formats. Basically, I don't like the trailing commas in the BED12 format (for fields 11 and 12). It doesn't make sense to me to allow it because it can lead to other issues. But I understand that it is technically allowed under BED12 formatting rules. 

The vote is now against me and so I have changed TAMA Merge to allow this formatting as well. I have just pushed the update so if you reclone it should work. Elsewise, you can just not include the trailing comma in your convertor. 

Let me know if it works ok for you. 

Thank you,
Richard

**Comment by rmenafra** [comment]
Hi Richard,
I pulled the latest version and indeed it worked (I could only test it on one of the 2 files because there is still one of the 20 fractions running tama_collapse!).
However when I look at the output I'm a bit confused:

- Fourth column of the bed file *_merged_annos.bed contains these identifiers: G13;G13.1
I thought it would use the name of the source I specified (being the hg38_ref)

- Same question stands for the file *_gene_report.txt, where the geneID in the first column is in the format G13, whereas I thought it would be pulled from the geneID of the source I indicated for the names.
I'm not sure if my expectations was wrong or something went "wrong", but the pipeline technically terminated without errors.
Best,
Roberta

-

**Comment by GenomeRIK** [comment]
Hi Roberta,

Can you copy paste:
1. The filelist.txt file
2. The command you use to run TAMA Merge
3. The last 10 lines of the terminal output
4. First 10 lines of one of the input files

Thank you,
Richard

**Comment by rmenafra** [comment]
Hi Richard,
sure! Even though the job output is named tama.collapse is in reality the tama_merge.
Let me know if you need any other info.
Thanks
Roberta 
[Archive.zip](https://github.com/GenomeRIK/tama/files/4176897/Archive.zip)

**Comment by GenomeRIK** [comment]
Hi Roberta,

Looks like the run did not finish. This is the error message from the terminal output:
"By default TAMA merge does not allow merging of duplicate transcript groups.
Duplicate transcript groups occur when different groupings of transcripts results in the same collapsed model.
If you would like to merge duplicate transcript groups please add -d merge_dup to the arguments."

So you need to re-run with "-d merge_dup".
Also I do not recommend running with default parameters for start and end wobble. You might want to try "-a 100 -z 100".

Let me know if you still have the ID issue after TAMA Merge runs successfully. 
You should see:
"TAMA Merge has completed successfully!" 

At the end of the terminal output if it runs successfully. 

Also check that the TAMA Collapse runs have this at the end of the terminal outputs:
"TAMA Collapse has successfully finished running!"

Cheers,
Richard

**Comment by rmenafra** [comment]
Hi Richard,
I rerun Tama merge with the options you mentioned (-d merge_dup -a 100 -z 100)
Now the job log ends with "TAMA Merge has completed successfully!"
However the gene ID in the first column of the *merged_annos_gene_report.txt is still in the format G1;G2 here the first few lines:
gene_id	num_clusters	num_final_trans	sources	chrom	start	end
G1	2	2	hg38_ref	chr1	11868	14409
G2	3	3	0_hr_split_1,hg38_ref	chr1	14403	29570
G3	3	3	hg38_ref	chr1	29553	31109
G4	2	2	hg38_ref	chr1	34553	36081
Do you know why that happens?
Thanks in advance and let me know if you need any file.

**Comment by GenomeRIK** [comment]
Hi Roberta,

Apologies for the delay, I have been at a conference this week. The Gene ID's pulled from the reference annotation are only represented in the main annotation BED file. You can use the main bed file as a map file to link the TAMA ID's to the Ensembl ID's. The reason this is not done in gene report is because there are cases where you have bridging transcripts which sort of "combine" multiple genes. So the gene classification in TAMA uses a very simple definition for a gene loci which is all transcripts that overlap on the same strand. This means that a single TAMA gene ID could be used for several Ensembl genes. So this would be a one-to-many scenario. Likewise you can get a many-to-one scenario if the bridging transcript in the Ensembl annotation. And you can even get a many-to-many scenario as well. 

So it is a bit dangerous to have Ensembl gene ID's shown in the gene report file because this does not capture the true nature of what is going on transcriptionally. 

In the main annotation BED file, a transcript model will only inherit the named annotation ID if it matches on the transcript level. 

If you still want this type of information, I can add it in as an option but I am not sure this is exactly the type of information you are really looking for. If you can tell me what you are trying to do with this information, I can maybe suggest another way of doing it. 

Thank you,
Richard

**Comment by rmenafra** [comment]
Hi Richard,
thanks for your reply, none of my gene.ID in the main annotation bed file matches the ensemble genes, so I found this quite odd. 
The aim for now since I have two different conditions (unstimulated and after stimulation) is to be able to compare them having a unique annotation, therefore I need the isoforms to be linked to the "known" gene name (where it's possible) or eventually classify them as novel.
Best,
Roberta

**Comment by GenomeRIK** [comment]
Hi Roberta,

That's odd because I tried using TAMA Merge on the annotation file you sent me and it worked. Have you tried recloning the repo? Also don't use underscores in the source name. I use underscores for name delimiters.

Cheers,
Richard

**Comment by rmenafra** [comment]
>  Also don't use underscores in the source name. I use underscores for name delimiters.
Ah, that's it! I totally used underscores in the source names (especially merging 20 files)...I didn't know I couldn't...now it works, thanks!

**Comment by GenomeRIK** [comment]
Ok yeah sorry I made a mistake in the wiki manual when describing this. I've just changed it to clarify. 

Is that all for this issue thread? If so I'll close the thread. You can still reference it in the closed issues page.

Thank you,
Richard
