### ISSUE TITLE
stops/freezes at high coverage regions

### ISSUE THREAD

**Issue by HegedusB** [GenomeRIK/tama#22]
Hi Richard,

I am sorry to bother you again. I have an another problem. When I am using a larger data set (~5M reads) tama just stops/freezes when it reaches highly covered regions. High coverage means 30000 reads aligned on to a gene coding site. I split the alignment (sam) with you "tama_mapped_sam_splitter.py" into 10 pieces but this do not resolved the problem. When I tried to collapse the piece which contains the highly covered gene region the tama just freezes when arrived to that region. 
What do you suggest? How can I resolve this problem? Should I cut the alignment (sam) file into smaller pieces?

Thanks for your help!
Cheers,
Botond

**Comment by HegedusB** [comment]
I am sorry. The problem is with a gene which has a 454073 read coverage.

**Comment by GenomeRIK** [comment]
Hi Botond,

454,073 reads is a lot of coverage for a single gene!

Is this from a single sequencing run or are you processing multiple runs together? What is the total number of reads for this processing run?

Unfortunately TAMA Collapse struggles with these situations since it uses a non-stochastic algorithm. I am trying to find a proper solution for this but until then there are some things you could try.

1. Split the run/runs into smaller files prior to mapping. So I assume this is Nanopore data in which case the reads should already by chunked into smaller groups of fast5 files. So I would use something like 500,000 read chunks for processing and mapping and then for running TAMA Collapse. You can then merge the TAMA Collapse results using TAMA Merge. 

The SAM splitter does not help in your situation because it will not split up the reads for a single gene. 

2. If your cDNA library was not 5' cap selected, first run TAMA Collapse with the "capped" mode. Then run TAMA Merge on the result using the "no_cap" mode. 

The reason the process is freezing is probably because it is using up too much memory for resolving read relationships in "no_cap" mode. So this method reduces the complexity in "capped" mode and then resolves 5' degraded models in the "no_cap" TAMA Merge.



If neither of these things work for you, I can create a special mode in TAMA Collapse for you that will essentially throw out extra reads for extremely high coverage genes. 

In the future, I plan on re-implementing the core algorithms in a faster language like C to deal with this. But I am not sure when that will be available.

Thank you,
Richard

**Comment by HegedusB** [comment]
Hi Richard,

This is from a single sequencing run. Luckily the ONT produced ~15M reads per run. The run was multiplexed. (It contained multiple cDNA samples). The sample which I try to collapse contains 4978868 5’ cap selected reads. Because the reads are cap selected I used “capped” mode and in our server we have 768 GB of memory. The memory was not the bottleneck. In another case, when the sample contained 3408412 reads this gene has 104922 read coverage and tama could resolve that collapsing problem (tama is currently running on that sample so I do not know if it can finish the whole collapsing process).
I will follow your suggestion. I will do separate alignments and merge together the separately collapsed transcripts.

Thanks a lot for the advice.
Cheers,
Botond

**Comment by GenomeRIK** [comment]
Hi Botond,

I am ashamed to say that for TAMA Collapse with an over-abundant gene and total reads at near 5 million 768 GB is still not enough. Believe me, I have been criticized for this. 

Hopefully the splitting solves your issue. If I have time I can see if there are any more optimizations I can do to reduce memory usage and run time. 

Let me know if the splitting works for you!

Cheers,
Richard

**Comment by HegedusB** [comment]
Hi Richard,

Interestingly not the memory is the limiting factor. I have 5 samples. Each of them has almost 4M reads, most of them have more than 4M. Tama collapsed two of them (all reads 3,4M, max gene coverage = 133817 reads; all reads 4,1M, max gene coverage = 100367). It freezes with two samples (all reads 5M, max gene coverage = 454073, all reads 4.1M, max gene coverage = 232688). And with one sample the tama could not read the sam file because the same "Genome seq is not the same length as query seq" error happened that I have reported previously (the same deSALT problem). 
I am just curious. Is there a coverage limit? Why it can not collapse more than 150000 reads. 

Cheers,
Botond

**Comment by GenomeRIK** [comment]
Hi Botond,

TAMA Collapse creates and destroys groups while processing reads for a single gene region. If you have a massive number of reads for a single gene loci what you will typically see is that two things are happening:

1. There are reads which bridge genes causing multiple genes to be grouped together. 
2. There is a lot of wobble walking between reads.

When this happens TAMA Collapse ends up creating and destroying a lot of groups which floods the memory. You can see for yourself by tracking the memory usage (not average mem usage) of TAMA Collapse for those runs. 

Since Nanopore data has a relatively high error rate, you see a lot more wobble occurring in the mapped reads. So one way you could deal with this is to use the LDE settings to remove reads with high error densities around the splice junctions. However, this may also filter out some gene models from your results if those genes only had low quality reads supporting them. 

I describe the wobble issue in my pre-print:
https://www.biorxiv.org/content/10.1101/780015v1

Could you send me the command line you are currently using to run TAMA Collapse?

Thank you,
Richard

**Comment by HegedusB** [comment]
Hi Botond,

Thanks for the explanation. I will reads the article again for sure.
This is the command what I am using:

tama_collapse.py -s input_sorted.bam -b BAM -f ref_genome.fasta -p NB01 -x capped -icm ident_map -a 50 -z 50

Cheers,
Botond

**Comment by GenomeRIK** [comment]
Hi Botond,

Ok you can try this:
tama_collapse.py -s input_sorted.bam -b BAM -f ref_genome.fasta -p NB01 -x capped -icm ident_map -a 50 -z 50 -sjt 20 -lde 2

This means that TAMA Collapse will throw out any read with more than 2 errors on either side of the splice junctions within 20 bp of the splice junctions. 

Feel free to tweak it as you see fit. This is fairly stringent so you may get a lot of genes removed using something this stringent. However the gene models that make it though will be higher quality. 

Also something that just occurred to me is that if deSalt is making a lot of micro exon mappings, there may be a lot of "alternative" transcript models in the mappings which are actually just erroneous micro-exon mappings. This would definitely cause issues with TAMA Collapse with respect to group creation/destruction and memory usage. So it may be worth while to take a look at the TAMA Collapse results from the runs that worked and look for genes with a high number of transcripts to see if you see this micro-exon expansion happening. If this is the case, then deSalt needs to be modified to deal with this. Or I could build a filtration method for assessing these situations. 

To find genes with large numbers of alternative transcripts, you can use this:
cat <bed file> | awk '{print $4}' | awk -F ";" '{print $1}' | uniq -c | sort -nr | less

Cheers,
Richard

**Comment by HegedusB** [comment]
Hi Richard,

Thanks a lot again! This is grate! I will try it for sure! I am using lordec in the polishing step. It do a great job, if the illumina read coverage is not to low or not to high on a region. Maybe this stringent approach wont cause to much harm.
Actually I have not seen many erroneous micro-exon mappings yet. The oposit is the problem. The deSALT has a problem with the mapping of really shorter exons (shorter than 8-9 bp), it produce insertion from them and stick them to the border of one of the splice sites, but do it way better than the other aligners.  

Cheers,
Botond

**Comment by GenomeRIK** [comment]
Hi Botond,

Just checking in and hope you are doing well. 

With regard to deSalt's behaviour you mentioned: 
"The deSALT has a problem with the mapping of really shorter exons (shorter than 8-9 bp), it produce insertion from them and stick them to the border of one of the splice sites"

This can actually cause a lot of wobble which makes it more difficult to process for TAMA Collapse. Hope the new LDE setting is working for you. Let me know if you have any issues with it. 

Cheers,
Richard

**Comment by HegedusB** [comment]
Hi Richard,

Thanks for your interest. The LDE setting worked fine. The run was faster than without it. Surprisingly, after some time, the run without the LDE setting finished successfully. For the future steps I used those data. Now I have stuck a little. I try to split those gene, which are created by merging slightly/largely overlapping transcripts which are originated from neighboring genes located on the same strand (overlapping UTR regions/readthrough). Besides that, we are trying to manually curate those gene models where some problems happened during the alignment (unaligned short exons, badly aligned non-canonical splice sites). These put out more than 10 percent of the genes. I try to produce a reliable reference annotation which I can use for a second alignment and tama merge run. Maybe after that I will have a good annotation for the further analyses.  
However, the tama worked fine! And thanks again for all of your help!

Cheers,
Botond

**Comment by GenomeRIK** [comment]
Hi Botond,

Ok that's great to hear! As for your gene splitting issue, I think I might actually have a solution for you now. I have been developing this with one of my collaborators. 

Basically it involves using the ORF/NMD pipeline to assign protein/Ensembl ID's to the transcript models and then re-arranging the ID's to use those for defining the gene relationships. 

It's a bit complicated but I explain it a bit in a recorded talk that will be available through the virtual SMRT Leiden conference (https://t.co/6d4GloVkyS?amp=1).

If you want to know more, you can open up a new issue about it and I can respond there. I have also started a blog to go over how to use TAMA to do these kinds of things. 

Ok I am closing this thread now. 

Thanks for using TAMA!
Richard
