### ISSUE TITLE
SAM parse off by one?

### ISSUE THREAD

**Issue by petersbrC** [GenomeRIK/tama#23]
Hello,

I am wondering if your sam parse section has an off-by one error present.  Hopefully I am missing something or some downstream correction.  Here's your code:

```
def trans_coordinates(start_pos,cigar):
    [cig_dig_list,cig_char_list] = cigar_list(cigar)
    end_pos = int(start_pos)
    exon_start_list = []
    exon_end_list = []
    
    exon_start_list.append(int(start_pos))
    
    for i in xrange(len(cig_dig_list)):
        cig_flag = cig_char_list[i]
        
        if cig_flag == "H":
            continue
        elif cig_flag == "S":
            continue
        elif cig_flag == "M":
            end_pos = end_pos + int(cig_dig_list[i])
            continue
        elif cig_flag == "I":
            continue
        elif cig_flag == "D":
            end_pos = end_pos + int(cig_dig_list[i])
            continue
        elif cig_flag == "N":
            #add exon end position to list (must be before updating end pos info)
            exon_end_list.append(end_pos)
            end_pos = end_pos + int(cig_dig_list[i])
            #add exon start
            exon_start_list.append(end_pos)
            continue
    #add last exon end position
    exon_end_list.append(end_pos)
    
    return end_pos,exon_start_list,exon_end_list

```
It looks like you are treating the sam file as being zero-based instead of one-based as in the specification.

Imagine that your transcript alignment begins with an exon of length 1...
```
end_pos = int(start_pos) # you initially define end_pos to be the same as start
# drop a bit into it...
elif cig_flag == "M":
  end_pos = end_pos + int(cig_dig_list[i])
  continue
```
a cigar match of length 1 should not change the end position from the start in 1-based coordinates but this code does.  

I don't think this would harm most boundary comparisons that are simply numeric because it would be systematic but it should affect reported features unless you are subtracting one from your end coordinates for say bed files to position it properly.  If you did any coding checks by grabbing sequences by these coords it would likely severely affect them unless there is a correction applied there too.

I noticed this due to a recent switch to deSALT since minimap2 was dropping small exons from its alignments. I was investigating this message from tama_collapse:
```
Error with exon end earlier than exon start
226925864	226925864

# observed when tama was processing two transcripts with these cigar strings that I've tokenized:
1S 25M 15754N 113N 93M 1864N 140M 425N 126M 85N 383M 1S
1S 25M 15754N 113N 93M 1864N 140M 425N 126M 85N 383M 1S
```
I get this message frequently and thus lose data.  There don't seem to be any single base exons here so my first guess which led to the coordinate system issue was wrong.  My actual issue looks to be that there are two introns with no intervening exons being reported in the cigar, the 1st intron is immediately followed by another which seems like an aligner bug.

Nonetheless, if someone is permitting one-based exons, the following shouldn't be an error when end equals start unless tama internally operates on python/bed style coords which it doesn't seem to.
Tama exits at this point.
```
if check_end <= check_start: # exon end must always be greater than exon start
            print("Error with exon end earlier than exon start")
```
I do see that there is a danger of division by zero if one assumes that exon length = check_end - check_start in a one-based coordinate system.

Am I missing something here?

Regards

**Comment by GenomeRIK** [comment]
Hello,

I'm not sure I completely follow what you are saying here but first regarding the error you are getting. 

As you observed it is caused by the contiguous N's in the CIGAR string from the deSalt BAM file.

I have logged this issue which you can find here:
https://github.com/ydLiu-HIT/deSALT/issues/25

Presumably it has been fixed now. I suspect you may not have the latest version of deSalt. This is definitely an error with how the CIGAR string was put together. 

As for the way I deal with the coordinates in TAMA Collapse, you are correct that I am converting it into my own coordinate system. And yes I convert it back to the BED coordinate system before writing out the coordinate values. 

I don't really understand what you mean by: 
"a cigar match of length 1 should not change the end position from the start in 1-based coordinates but this code does."

I am using my own coordinate system for this which is basically python zero base. An exon of length 1 should change the end position with respect to this situation. As for causing coordinate problems, I tested the outputs by comparing to public reference annotations. And I also tested using the ORF/NMD pipeline which would show lots of frame shift if there were 1 base error types in the output. 

If you find an error in the coordinate representation in the BED12 output file please let me know. 

The reason TAMA Collapse exits in the situation where the exon start is greater than the exon end is because this is indicative of erroneous mapping information. This is actually how we found the bug in deSalt in the first place. 

For a 1 base exon, the exon end will be greater by 1 than the exon start within my algorithm. 

I always try to make TAMA tools exit if there is a problem with the input data. Usually if there are issues with input data then it's not safe to continue processing because it is indicative that something is very wrong. 

Hope this makes sense and I really suggest you look at the issue I linked above. I think it may clarify some things. 

Cheers,
Richard

**Comment by petersbrC** [comment]
Thank you for the explanation.  Not a problem with TAMA, thank goodness!  Just my understanding of how TAMA was internally representing coords.  There is no issue with 1bp exons.  In the parsing code it looked like it was setting up off by one output but I found that was being corrected in format_bed_line().

No issues with exiting on weirdness, that's all good.

Thank you
