### ISSUE TITLE
BAM file is not supported for tama_collapse.py

### ISSUE THREAD

**Issue by yichangyu** [GenomeRIK/tama#40]
Dear TAMA developer,

I got an error saying `Please try again with complete arguments
Traceback (most recent call last):
  File "/data/group/lewseylab/home/cyi/tama/tama/tama_collapse.py", line 207, in <module>
    sam_file = opts.s[0]
TypeError: 'NoneType' object has no attribute '__getitem__'` when I run `tama_collapse.py` using this code `python tama_collapse.py -b my_sorted.bam -f my_fasta -p iso_set2 -x no_cap `. However, it works if I convert the bam file to sam file. Could you please take a look at this? Please let me know if you need more information.

Thanks,
Changyu

**Comment by yichangyu** [comment]
I just found this thread https://github.com/GenomeRIK/tama/issues/32#issue-681629203, so should I use `python tama_collapse.py -s both.aligned.sorted.bam -b -f my_fasta -p iso_set2 -x no_cap`?

**Comment by GenomeRIK** [comment]
Hi Changyu,

For BAM input you would need to use "-b BAM" in your TAMA Collapse command line.

You can find instructions in the wiki manual:
https://github.com/GenomeRIK/tama/wiki/Tama-Collapse

On that page:
-b BAM Use sorted BAM input instead of SAM. To enable this use this parameter "-b BAM". Default is SAM input. If you use a BAM input you must have pysam installed. SAM input runs do not require pysam.

Cheers,
Richard
