### ISSUE TITLE
log argument not work

### ISSUE THREAD

**Issue by yichangyu** [GenomeRIK/tama#41]
Dear TAMA developer,

I found the `-log` parameter is not working when I run `tama_collapse.py`. When I run the script with out `-log`, I did not see a log file when the run is finished. When I add the `-log log_on`, I kept get an error saying `Please use log_on or log_off`, and the run just stoped. Could you please take a look at this?

Thanks,
Changyu

**Comment by GenomeRIK** [comment]
Hello Changyu,

The log is output to the screen and not saved to file. So when you run tama_collapse.py you should see the log printing to the screen. You can capture to a file by piping the command to a file or if you are using a compute cluster with scheduler, the system typically makes a file with screen printouts. 

If you need help with this, let me know what sort of computing environment you are running TAMA in and I can tell you the appropriate way to get the log into a file. 

Also there is no "-log log_on" option since log_on is the default. I can see that the description on the wiki manual was confusing so I have now changed the wiki manual to make it more clear. Thank you for pointing out this issue with the manual. 

Cheers,
Richard

**Comment by yichangyu** [comment]
> Hello Changyu,
> 
> The log is output to the screen and not saved to file. So when you run tama_collapse.py you should see the log printing to the screen. You can capture to a file by piping the command to a file or if you are using a compute cluster with scheduler, the system typically makes a file with screen printouts.
> 
> If you need help with this, let me know what sort of computing environment you are running TAMA in and I can tell you the appropriate way to get the log into a file.
> 
> Also there is no "-log log_on" option since log_on is the default. I can see that the description on the wiki manual was confusing so I have now changed the wiki manual to make it more clear. Thank you for pointing out this issue with the manual.
> 
> Cheers,
> Richard

Hi Richard,

Yes, I can see the log in the screen. I think it would be great to record these information in a separate log file. I am running TAMA in a cluster interactively, and the OS of the cluster is  `Linux x86_64 GNU/Linux`. It would be great if you can tell me how to pipe the log into a file.

Thanks,
Changyu

**Comment by GenomeRIK** [comment]
Hi Changyu,

If you are using the cluster interactively then you should be able to output the screen prints and view them on the screen while it is being generated by using this command:
command | tee /path/to/file

See this website for more info:
https://www.howtogeek.com/299219/how-to-save-the-output-of-a-command-to-a-file-in-bash-aka-the-linux-and-macos-terminal/

Please let me know if this does not work for you. 

Cheers,
Richard
