### ISSUE TITLE
Odd output from Tama Merge

### ISSUE THREAD

**Issue by SziKayLeung** [GenomeRIK/tama#43]
Hello Richard, 

I'm trying to merge 12 of my Iso-Seq samples using TAMA Merge (admittedly, from Cupcake collapse - I have generated the bed12 file from Cupcake's gtf and feed that into TAMA Merge). 

The script runs (very quickly, within a minute!), and finishes with "TAMA Merge has completed successfully!" but the files for the gene_report.txt and trans_report.txt look very odd and appears to be missing columns.
![image](https://user-images.githubusercontent.com/33493350/102136311-23461280-3e51-11eb-815e-d8d5df9c19b2.png)

`python tama_merge.py -f filelist.txt -a 50 -z 50 -m 20 -p Individual &> Tama_merge.log`
(last updated tama_merge.py script: 2020/07/21)

The output bed file seems to be correctly labelled though: 
![image](https://user-images.githubusercontent.com/33493350/102137129-3e655200-3e52-11eb-81e3-51524e415711.png)

Attached is my filelist and log file. 

Any guidance on this would be greatly appreciated, 

Thank you, 
Szi Kay

[Individual_Tama_filelist.txt](https://github.com/GenomeRIK/tama/files/5691628/Individual_Tama_filelist.txt)
[Tama_merge.log](https://github.com/GenomeRIK/tama/files/5691629/Tama_merge.log)

**Comment by GenomeRIK** [comment]
Hi Szi Kay,

Thank you for using TAMA!

Could you copy paste some lines from the input BED files here? It looks like there might be some issues with the ID format.

Cheers,
Richard

**Comment by SziKayLeung** [comment]
Hello Richard, 

Thank you for the prompt reply! Please see below a snapshot of one of the input BED files. 

![image](https://user-images.githubusercontent.com/33493350/102257956-4a5e1c00-3f05-11eb-8929-5423120b63e3.png)

Thank you, 
Szi Kay

**Comment by GenomeRIK** [comment]
Hi Szi Kay,

Ok I have a suspicion of what is going on here but I need some more info to confirm. 

Could you copy paste the contents of the filelist.txt file?

Thank you,
Richard

**Comment by SziKayLeung** [comment]
Hello Richard, 

Please find below the contents of the filelist.txt file (I've also attached it in my first post) 
![image](https://user-images.githubusercontent.com/33493350/102348895-6c55ae00-3f9a-11eb-9ec1-65f14eaa321a.png)

Thanks!
Szi Kay

**Comment by GenomeRIK** [comment]
Hi Szi Kay,

Sorry I didn't see the file attachments in the first post. 

I think I have figured out what was wrong. 

There were 3 issues:
1. You had DOS style new line characters in your filelist file. You can check this by using:
  cat -A Individual_Tama_filelist.txt

So you will see '\M' at the end of each line. This can cause a lot of issues when running tools on linux so I suggest you check files for this before running anything. This usually happens when you try to copy paste a file from a windows system or if you create the files in a windows system and move it to your linux system. 

I have updated TAMA Merge to check for the occurrence of the DOS new line characters now. 

2. You had trailing spaces at the end of some of the lines in the filelist file. You can see them when you run the above command. 

I have updated TAMA Merge to check for the occurrence of the spaces in the filelist file now. 

3. You are using "no_capped" instead of "no_cap" in the filelist file. I actually already fixed this issue with TAMA Merge so I think you are using an old version. 

So I suggest recloning TAMA and fixing your filelist file and try running TAMA Merge again. 

Please let me know if this fixes your issue. 

Cheers,
Richard

**Comment by SziKayLeung** [comment]
Hi Richard, 

Thank you so much for picking up the issue with the filelist.txt. I have fixed the rile and updated TAMA, and works perfectly. Thank you!

Best, 
Szi Kay

**Comment by tky199996** [comment]
> 嗨理查德，
> 
> 非常感谢您提出 filelist.txt 的问题。我已经修复了这个问题并更新了 TAMA，并且运行良好。谢谢你！
> 
> 最好的， 施凯
Hello, I saw you asked a question about tama_merge.py before. I recently encountered a similar situation to you. I first used the tama_collapse.py script to collapse, and then got the bed file, but when I used tama_merge.py When the script processes the bed file, an error is reported. Can you help me solve this problem? Thank you.
![截屏](https://github.com/GenomeRIK/tama/assets/120616828/d0c13ff1-1178-4010-883e-4c63b2859caf)

![截屏2](https://github.com/GenomeRIK/tama/assets/120616828/42a5796a-621c-442a-bb90-65658b1042b9)
