### ISSUE TITLE
Can 'tama_flnc_polya_cleanup.py'  input/output FASTQ or BAM format?

### ISSUE THREAD

**Issue by frabanal** [GenomeRIK/tama#45]
I am analysing Iso-Seq libraries produced with Lexogen's Teloprime v2. In the process, I've taken full advantage of Richard Kuo's suggestion in [Twitter](https://twitter.com/GenomeRIK/status/1179788262187110401) to employ "tama_flnc_polya_cleanup.py" instead of "isoseq3 refine --require-polya --min-polya-length 12 ...". In fact, I recover **82-99% more FLNC reads with the TAMA script than with the isoseq3 --require-polya approach**.  Big thanks for that!

Unfortunately, my polyA-trimmed transcripts are only available in FASTA format (not even FASTQ), and that limits my possibilities for downstream application (e.g., isoseq3 cluster, isONclust).

I was wondering if the "tama_flnc_polya_cleanup.py" could input/output a different format (i.e., FASTQ, BAM) so that the quality information is preserved. Alternatively, a convertor could be added since the BQ info is in the BAM from the "isoseq3 refine" step. 

Kind regards, 

Fernando

**Comment by aleksandrakornienko** [comment]
Having the same question!

**Comment by GenomeRIK** [comment]
Hi Fernando,

Apologies for taking so long to get back to you. I was busy with another project this year. I generally do not recommend running cluster but if you still need the fasta to fastq convertor for isONclust let me know and I'll see what I can do. 

Cheers,
Richard

**Comment by AbeerMM** [comment]
Hi @GenomeRIK 
I'm wondering if there is any update on this issue. I'm having the same problem. I use isoseq3 tools and after running isoseq3 refine, I convert the bam file to fasta file, and then run the python script. 

The problem is my current workflow includes cluster then collapse from isoseq3. The only way I was able to run cluster with is by aligning the fasta file to get the bam file and use it next. However, I don't think this is right..
