### ISSUE TITLE
Improve annotation

### ISSUE THREAD

**Issue by cculma** [GenomeRIK/tama#47]
Hi Richard, may you help me with this issue?

I have my bed file annotated using `TAMA GO: ORF and NMD predictions`, `Uniprot_100 DB` and `diamond BLASTP`. However, different isoforms from the same gene_id have different Unirprot IDs:

```
gene_id	isoform	gene	trans_length_flag	blastp_match_flag
G5	G5.1	A0A445DLR5	5prime_degrade	bad_match
G5	G5.2	A0A4P1R3Y6	full_length	bad_match
G5	G5.3	A0A151T2D9	full_length	bad_match
G5	G5.4	A0A2G3AYH1	full_length	bad_match
G5	G5.5	A0A2G3AYH1	full_length	bad_match
G5	G5.6	UPI0010A4D799	full_length	90_match
G5	G5.7	UPI0010A4D799	full_length	90_match
G5	G5.8	A0A445DLR5	full_length	bad_match
G5	G5.9	A0A445DLR5	full_length	bad_match
G6	G6.1	A0A314Z1D9	5prime_degrade	bad_match
G6	G6.2	A0A314Z1D9	5prime_degrade	bad_match
G6	G6.3	A0A224X4A1	5prime_degrade	50_match
G6	G6.4	A0A1R3HQH4	5prime_degrade	90_match
```

I want to use something like `ifelse` to unify `gene` annotation based on the highest `blastp_match_flag`. i.e. annotate all isoforms G6 as A0A1R3HQH4. Is that possible? 

Best,

Cesar

**Comment by GenomeRIK** [comment]
Hi Cesar,

There are some "good" reasons why this occurs. Usually due to gene families or common motifs. However, it is not so simple for choosing the correct protein to match. It may be worth using TAMA merge with a reference annotation to stack on the Gene ID's from the reference. This will be a type of fix to your problem but arbitrarily choosing one protein match over another for each transcript is not usually a good idea. 

Cheers,
Richard
