### ISSUE TITLE
Clarification splitting large SAM file to run collapse and then merge

### ISSUE THREAD

**Issue by J-Calvelo** [GenomeRIK/tama#62]
Hello. This must be somewhat basic but I'm not entirely sure from this line on the wiki if I should set -a to 0 or run it with default parameters.

`You can merge the resulting bed12 files using TAMA Merge (**with no wobble**) and the transcript and gene models will be identical to running TAMA Collapse on the whole SAM file. `

Thanks

**Comment by J-Calvelo** [comment]
I'm trying to annotate a genome using TAMA and PACBIO isoseq data. But the after selecting the full isoforms I'm left with 1708667 and I need to split them to save memory and then merge them again.

**Comment by J-Calvelo** [comment]
After running isoseq3 refine

**Comment by lscdanson** [comment]
Hi I also would like to seek clarification over what you mean by "no wobble". I've split my bam file for the TAMA collapse step and am now trying to merge the split bam files back together using TAMA Merge. Does that mean I should set all three of the -a -m -z options as 0 instead of the default values? 

Many thanks.

**Comment by lscdanson** [comment]
Also if I'm simply merging the split bam files back together (all no_cap), should I set the "merge_priority" in the filelist.txt as "1,1,1" or "2,1,1"?
