### ISSUE TITLE
Can TAMA merge be used to combine a short read assembly and long read data without a reference genome?

### ISSUE THREAD

**Issue by FarrahKhan1400** [GenomeRIK/tama#72]
Hi Richard,

I am just wanting to follow up on whether I've understood this correctly: 'Comparing your Iso-Seq data to the reference annotation (or short read RNAseq annotation)'

I have short reads that I've assembled using Trinity. I may collapse using Grouper depending on your answer.

And I have long read data that has been run through isoseq3, Cogent and collapsed via cDNA_Cupcake.

I do not have a reference genome. 

My ultimate goal is to use the non-redundant isoform set from the isoseq3-cogent-cdna_cupcake mainly, and then add any additional. unique transcripts from my short read assembly. Using the total set of transcripts I would then annotate and this would serve as my reference transcriptome for differential expression analysis.  

Is it possible to merge these two datasets without a reference genome using TAMA merge? If so,

1) Do I merge the pre-collapsed transcripts? 
2) Do the headers from the trinity assembly need to 'match' the set of long read isoforms?

Thanks

Kind regards,
Farrah Khan

**Comment by GenomeRIK** [comment]
Hi Farrah,

This is a bit of weird one so I will need some more info. Right now what is the format of your transcript models? 

Also I am not sure I understand why you used Cupcake collapse after Cogent? What did you use as input to Cupcake collapse and what command did you use?

Cheers,
Richard

**Comment by FarrahKhan1400** [comment]
Hi Richard,

Thanks for your response.

The format of both transcript models is in fasta format.

Cupcake collapse is the recommended next step after Cogent. The
high-quality isoforms are mapped against the cogent fake genome and then
they are collapsed as far as I understand it. Here are the exact commands I
used: collapsing redundant isoforms
<https://github.com/Magdoll/Cogent/wiki/Tutorial%3A-Using-Cogent-to-collapse-redundant-transcripts-in-absence-of-genome#collapsing-redundant-isoforms>
(hq_transcripts.fasta
is the output of the iso-seq3 pipeline).

Kind regards,
Farrah

**Comment by GenomeRIK** [comment]
Hi Farrah,

Ok I think I understand now what you are trying to do. 

The issue I see here is that since you do not have a genome assembly, it is going to be a bit challenging to merge the short read trinity models with the Iso-Seq Cogent models. Essentially you made a pseudo assembly using Cogent but that onyl covers the isoforms seen in your Iso-Seq data. So any Trinity models that do not have their exons covered in the Cogent assembly will be lost. 

It would help to understand what the downstream use for this would be. Could you provide some info on that? For instance, are you planning on using something like Kallisto or Salmon for the Diff Gene Exp analysis?

I suspect however that maybe what you want to do is actually map your Trinity transcript sequences onto the Cogent assembly using Minimap2 with splice awareness. 

For the transcripts that map, you could then use TAMA Merge to merge them with the Iso-Seq models that are based on the Cogent assembly. You would then extract the fasta sequences for the non-redundant models and combine it with the fasta sequences of the Trinity models that did not map or had poor mapping. This combined fasta model would then serve as your transcriptome for downstream analyses. 

You could also run the resulting models through the TAMA ORF/NMD finder pipeline to get info on matching known proteins. 

I hope this helps. 

Cheers,
Richard
