### ISSUE TITLE
Help for explaination to PolyA results from TAMA collapse

### ISSUE THREAD

**Issue by linglingtingfei** [GenomeRIK/tama#8]
Hi @GenomeRIK,
I first mapped high-quality FLNC reads to the genome and got sam file for next running TAMA collapse. 
I'm a little confused with PolyA results. if you collapsed some similar isoforms as one isoform, like G3959.1(see below screenshot), Why there are some different polyA sequence for G3959.1?  Isn't one isoform one polyA sequence? 
By the way, I compared the polyA results got from TAPIS and TAMA, the number of polyA is totally different,  TAMA was far less than TAPIS. Could you explain the principle of this program for identifying polyA? or which software do you recommend? I'd really appreciated that.
ling
![image](https://user-images.githubusercontent.com/20789616/48109249-9e579a80-e281-11e8-8a0b-ea89b3bd3c00.png)

**Comment by GenomeRIK** [comment]
Hi Ling,

I'm going to bullet point my replies to your questions to make it easier to roganize:

>>Why there are some different polyA sequence for G3959.1? Isn't one isoform one polyA sequence?

The collapse tool merges the models from different mapped reads if the mapped reads have a structure that is similar enough to each other. So what you see in the Poly-A output file is the ID for the mapped read in the first field and the ID for the collapsed transcript model in the second field. Since the mapped reads for a single collapsed transcript model can have slightly different 3' ends, the poly-A prediction will be different. This is because the Poly-A prediction starts from the 3' end of the mapped read. You can see in your image that the genomic Poly-A for mapped reads from the same transcript shows a slight shift in where the 3' end of the mapped reads were. 

 >>By the way, I compared the polyA results got from TAPIS and TAMA, the number of polyA is totally different, TAMA was far less than TAPIS. Could you explain the principle of this program for identifying polyA? or which software do you recommend?

TAMA and TAPIS use different ways of finding possible Poly-A truncation sites. I am not sure exactly how the TAPIS algorithm works in this regard but from what I have seen, it looks at a gene region and then tries to find peaks of poly-A stretches within the genomic sequence for that gene region. The default width threshold for the peaks is 5 nucleotides. 

TAMA uses a different approach. In TAMA Collapse, the 3' end of each mapped read is analyzed to see if there is a genomic region immediately following the 3' end that has a stretch of genomic Poly-A. The default threshold is 70% A and the default length of the region examined is 20 bp. I have updated the TAMA Collapse wiki to show this information. Also I will be releasing a new version of TAMA Collapse soon which will allow you to choose the thresholds. 

So it may be that TAPIS gives more genomic Poly-A sites because it is including sites that do not correspond to any mapped reads. 

The point of the Poly-A output file in TAMA is to show mapped reads which may be the result of truncated priming during the RNA to cDNA processing stage. This can happend because the primers used for the reverse transcriptase contain an Oligo-dT region for capturing the poly-A tail of the transcript. However, if the transcript has an internal stretch of A's then the primer could theoretically attach to that stretch instead of the true 3' end.   

It can also be used to examine the possibility of genomic contamination dur to the Poly-A priming. 

For more information on this effect please read this paper which describers the rationale behind the genomic Poly-A test:
https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-017-3691-9

Another point that I think is important to clarify is that these Poly-A files from TAMA and TAPIS are used for filtering out possible fake termination sites from your data. They are not used to directly look at APA. Instead they are used to clean up your data so your APA analysis is more accurate. 

In the case of TAMA Collapse, the Poly-A file only shows possible truncation events but does not remove them from the final output. You can remove them yourself after coming to your own conclusions about what should be done. 

Please let me know if anything I said here was unclear or if you have any more questions. 

Thank you,
Richard

**Comment by GenomeRIK** [comment]
Hello Ling,

Did my response answer your question? If not, could you clarify? If it did, I will close this issue. 

Thank you,
Richard

**Comment by linglingtingfei** [comment]
Hi Richard，
Your detailed answers help me a lot. Thanks a bunch.
Ling 


| |
黄玲玲
|
|
邮箱：linglingtingfei@163.com
|

签名由 网易邮箱大师 定制

On 11/14/2018 23:47, GenomeRIK wrote:

Hello Ling,

Did my response answer your question? If not, could you clarify? If it did, I will close this issue.

Thank you,
Richard

**Comment by GenomeRIK** [comment]
Ok glad I could help!
