### ISSUE TITLE
Error in TAMA merge

### ISSUE THREAD

**Issue by anchonggen** [GenomeRIK/tama#81]
Hi,
I ran TAMA collapse successfully but failed to run TAMA merge with parameters “-a 300 -z 300 -m 30 -d merge_dup” and the error was shown below. 
![下载](https://user-images.githubusercontent.com/115862778/195972126-94038d29-f9e3-4f6c-a39d-473518ab6426.png)
![下载 (1)](https://user-images.githubusercontent.com/115862778/195972140-c6fae24f-39bc-433d-abf2-e9b8784ccec4.png)

Could you please share your thoughts on what could be wrong here?

Thanks a lot!

**Comment by GenomeRIK** [comment]
Hello,

Thank you for using TAMA.

The issue here is that you are using the same source naming for each of the input annotation files. 

You should have a unique source name in the foilelist file for each bed file. I recommend naming each after the tissue as per the name of the bed file. 

For example:
blood.bed    capped     1,1,1    blood
feliver.bed    capped     1,1,1    feliver
felung.bed    capped     1,1,1    felung
kidney.bed    capped     1,1,1    kidney

Let me know if that does not work. 

Thank you,
Richard

**Comment by anchonggen** [comment]
Thank you, Richard. The problem has been resolved.
