### ISSUE TITLE
using a masked or unmasked genome?

### ISSUE THREAD

**Issue by idarolti** [GenomeRIK/tama#88]
When using IsoSeq data for transcriptome annotation, do you recommend masking the genome for repeats beforehand or using an unmasked version? I know that with short-read data unmasked repeats can cause issues with gene predictions but I am not sure if the same issues are expected with long-read IsoSeq data. I did not see this mentioned anywhere in the paper or the github page. Any advice would be greatly appreciated!

Thanks, 
Iulia

**Comment by GenomeRIK** [comment]
Hello Iulia,

Thank you for reaching out to me. With respect to masking repeats, it is probably better to do so. However, long read RNA data is more resilient to issues with repeat regions in the genome. Because you get full length RNA sequences, the sequences will typically map more uniquely and not in the repeat regions. Masking repeats is more of a short read thing because of the multi-mapping issues with short read data. 

Hope this helps!
Richard
