### ISSUE TITLE
TAMA GO: Read Support

### ISSUE THREAD

**Issue by anchonggen** [GenomeRIK/tama#90]
Hi,

I tried to generate read support for TAMA merge run, but it reported an error as below. Could you please help me solve this problem?

![image](https://user-images.githubusercontent.com/115862778/203963920-e19d36fe-5048-4b06-949d-f7c5ecdfbdf4.png)
![image](https://user-images.githubusercontent.com/115862778/203964472-519107a1-ef73-4d33-a9a7-a908354d5769.png)

Thank you!

An

**Comment by GenomeRIK** [comment]
Hello An,

It looks like you are trying to run this command in your TAMA tools folder. This is not recommended as you should not be saving output files into your git clone. 

I suspect the reason this is not working is because your specified input files are not in the same folder as where you are running this command from.

You should move your analysis outside of the TAMA folders and call TAMA using the path to the script you want to run. 

You will need all the input trans_read files to be in the same folder as where you are running this command from so the tool can find those files. 

This is one of the core concepts of using Linux and command line tools. It might be good to get some help from someone for basic command line usage. 

Thank you,
Richard

**Comment by anchonggen** [comment]
Hi Richard,
I rerun it again outside the Tama folder, but it still reported the same error. 
![image](https://user-images.githubusercontent.com/115862778/204071107-d6bc4261-c2c1-432b-b7ff-17da0a10ff2a.png)

Thank you.
An

**Comment by GenomeRIK** [comment]
Hi An,

Are all the input files in the same folder as where you are running the command from? Can you show me a screen shot of the folder contents?

Thank you,
Richard

**Comment by anchonggen** [comment]
yes, all input files are in the same folders as shown and highlighted here
![image](https://user-images.githubusercontent.com/115862778/204071256-2c4dcf11-a3ea-424f-ae18-fc15ab31b63d.png)

**Comment by GenomeRIK** [comment]
Hi An,

Is there by any chance an extra empty line in your filelist.txt file?

Could you send that file to me?

Thank you,
Richard

**Comment by anchonggen** [comment]
Hi Richard,

I typed it in excel and saved it in tab-delimited format, as shown below.
[filelist.txt](https://github.com/GenomeRIK/tama/files/10095670/filelist.txt)

Thank you,
An

**Comment by GenomeRIK** [comment]
Hi An,

Ok I see, that is the problem. You have empty lines and improper formatting. Could you recreate the file in the linux environment? You can just use Nano.

You can use "cat -A filelist.txt" to see if you have improper hidden formatting issues. 

Also a note, in general it is a bad idea to create input files in a windows environment for use with software that is intended to be run on linux because windows tools can add invisible formatting that messes things up.

Thank you,
Richard

**Comment by anchonggen** [comment]
Hi Richard,

Thanks for your hints. As you said, I found Excel added invisible formatting "^M" before "$" at the end of each line, which made them unable to be recognised. 

Kind regards,

An

**Comment by GenomeRIK** [comment]
Hi An,

I am assuming this issue has been resolved so I will close this thread now. You can reopen it if you are still having this issue. 

Thank you,
Richard
